### ISSUE TITLE
Lumper youtrack export problem

### ISSUE THREAD

**Issue by piskacek1** [agapoff/Lumper#1]
Logged to YT successfully
Got error while exporting issues
Exported issues: 
Users found in project

using YT6.5 and HTTPS

**Comment by agapoff** [comment]
Try to run the script with --debug option.

**Comment by piskacek1** [comment]
./migrate.pl --debug
Logged to YT successfully
$VAR1 = [
          'YTSESSIONID=pnmo6b5vhz7bvnn59zaa70f9;Path=/;Secure;HttpOnly',

'jetbrains.charisma.main.security.PRINCIPAL=NDZjNzVjYzdlYUkcTE1OWQ5YzVkY2NjYjhmNDU1MjBhMzAxZGNlNDMxZjhhZjhiNDE2NmE2YmRjYjEyMWE2MDEwYzpwbGluZGE;Path=/;Expires=Fri,
26-May-2017 06:50:20 GMT'
        ];
Project is defined in constructor. So I am going to get the metadata for
project OPER
$VAR1 = {
          'fields' => {
                        'Sub-task' => {
                                        'Issue Type' => 'issuetype',
                                        'Attachment' => 'attachment',
                                        'Assignee' => 'assignee',
                                        'Priority' => 'priority',
                                        'Due Date' => 'duedate',
                                        'Parent' => 'parent',
                                        'Reporter' => 'reporter',
                                        'Summary' => 'summary',
                                        'Time Tracking' => 'timetracking',
                                        'Labels' => 'labels',
                                        'Project' => 'project',
                                        'Server' => 'customfield_10109',
                                        'Description' => 'description'
                                      },
                        'Task' => {
                                    'Reporter' => 'reporter',
                                    'Summary' => 'summary',
                                    'Priority' => 'priority',
                                    'Due Date' => 'duedate',
                                    'Assignee' => 'assignee',
                                    'Attachment' => 'attachment',
                                    'Issue Type' => 'issuetype',
                                    'Description' => 'description',
                                    'Server' => 'customfield_10109',
                                    'Project' => 'project',
                                    'Labels' => 'labels',
                                    'Time Tracking' => 'timetracking'
                                  }
                      },
          'fieldtypes' => {
                            'Labels' => 'array',
                            'Time Tracking' => 'timetracking',
                            'Server' => 'string',
                            'Project' => 'project',
                            'Description' => 'string',
                            'Issue Type' => 'issuetype',
                            'Assignee' => 'user',
                            'Attachment' => 'array',
                            'Parent' => 'issuelink',
                            'Reporter' => 'user',
                            'Summary' => 'string',
                            'Due Date' => 'date',
                            'Priority' => 'priority'
                          }
        };
Let's check JiraPasswords
plinda OK

Proceed? (y/N) y
https://youtrack.test/rest/export/OPER/issues?max=10000
Got error while exporting issues
Exported issues:
Users found in project


2016-05-25 16:00 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
I have added some debug information if the YT export fails. Please pull the changes and run the script again. We'll see why the exporting fails.
Or you can try to query https://youtrack.test/rest/export/OPER/issues?max=10000 by yourself and see if you are able to get the XML.

**Comment by piskacek1** [comment]
https://youtrack.apollogames.com/rest/export/OPER/issues?max=10000
Got error while exporting issues
<?xml version="1.0" standalone="yes"?><error>You must be
administrator.</error>
403 Forbidden
but I have administration privileges or i need root privileges in youtrack
??

2016-05-26 9:26 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by piskacek1** [comment]
GET
https://youtrack.test/rest/export/OPER/issues?max=1000000&comments=1000000  *i
using same users in your scipt*
?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<issues>
    <issue>
        <field name="Priority">
            <value>3 - Low</value>
        </field>
        <field name="Severity">
            <value>Normal</value>
        </field>
        <field name="Assignee">
            <value>jklarek</value>
        </field>
        <field name="State">
            <value>Closed</value>
        </field>
        <field name="Resolution">
            <value>Not an issue</value>
        </field>
        <field name="Due date"/>
        <field name="Server"/>
        <field name="Waiting for"/>
        <field name="numberInProject">
            <value>1</value>

2016-05-26 9:26 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
The problem is that your YT returns cookie YTSESSIONID, not JSESSIONID. And Lumper was not ready for that.
I'va made some updates. Please pull the changes and try again.

**Comment by piskacek1** [comment]
Will import issue OPER-1
$VAR1 = {
          'watcherName' => 'User: id = 25-44[up-to-date]',
          'Resolution' => 'Not an issue',
          'Severity' => 'Normal',
          'numberInProject' => 1,
          'Priority' => '3 - Low',
          'comments' => [
                          {
                            'created' => '1385371010872',
                            'text' => 'test comment',
                            'author' => 'plinda'
                          }
                        ],
          'reporterName' => 'root',
          'updated' => '1386340577076',
          'State' => 'Closed',
          'created' => '1385043137606',
          'permittedGroup' => 'KOLO s.r.o.',
          'summary' => 'test',
          'Assignee' => 'plinda',
          'resolved' => '1386340577071',
          'updaterName' => 'plinda',
          'description' => 'TEST,
uzivatel Petr Linda'
        };
$VAR1 = undef;
{"fields":{"summary":"test","labels":[],"assignee":{"name":"plinda"},"priority":{"name":"Medium"},"description":"[Created
by root Thu Nov 21 15:12:17 2013]\nTEST,\nuzivatel Petr
Linda","reporter":{"name":"plinda"},"project":{"key":"OPER"},"issuetype":{"name":"Task"}}}
201 Created
{"id":"57633","key":"OPER-8936","self":"
https://jira.test/rest/api/latest/issue/57633"}
OPER-8936
Created issue OPER-8936



2016-05-26 10:49 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by piskacek1** [comment]
I thinks problem is here *description":"[Created by root Thu Nov 21
15:12:17 2013]\nTEST,\nuzivatel Petr
Linda","reporter":{"name":"plinda"},"project":{"key":"OPER"},"issuetype":{"name":"Task"}}}*

2016-05-26 10:49 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by piskacek1** [comment]
thanks for your very good support

2016-05-26 12:13 GMT+02:00 Petr Linda <petr.linda@apollogames.com>:

**Comment by agapoff** [comment]
Lumper does not set the issue key - Jira sets it by itself. Jira takes the largest used number in project and increases it by one while adding a new issue. Lumper just gets this key from Jira and shows it.
So try to drop the OPER project in Jira and recreate it. Thus Jira will start creating the issues from OPER-1.

**Comment by piskacek1** [comment]
super its OK but i have one issue ticket closed in youtrack is in jira TODO
not CLOSED

2016-05-26 13:06 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
In order to set appropriate Resolutions for some States you should configure your Jira workflow accordingly. 
For example if you'd like the Status Done to set the Resolution as Done you should add a Post Function to the transition leading to Done status. The Post Function is called "Update issue field" - just configure it to set the Resolution field.
If you'd like to set the Resolution depending on the YT issue status then you need to define the %StatusToResolution in Lumper's config file and add the Resolution field to the Jira project's screens (so Lumper will be able to edit Resolutions).

**Comment by piskacek1** [comment]
Its ok I modify JIRE server :) but I have next issue
{"errorMessages":[],"errors":{"labels":"Field 'labels' cannot be set. It is
not on the appropriate screen, or unknown."}} I not uderstand :( why?
Thanks


2016-05-27 8:58 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
Hard to say. You can set $exportTags to "false" in config.pl in order to skip creating the labels. Or you could investigate this issue further. Jira says that it is now aware of the 'labels' field. That's strange.

**Comment by piskacek1** [comment]
Hi Vitaly,
I need your support :(. We can leave those to modify the script for me?
I need to export and import data by Issue Id. Is it even possible ?
It's a major
adaptations script for you?
It's the last thing I need for the migration is completed.

Thanks



2016-05-27 19:19 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
You should read the documentation more carefully. The script has such arguments as --skip and --maxissues. For example if you'd like to export issue MYPROJECT-234, then just run the script as follows:
./migrate.pl --skip=233 --maxissues=1

**Comment by piskacek1** [comment]
I need to create the same number JIRE slip as import opera-34 and not a
support-2348th It is possible using API?

export import log
Will import issue OPER-34

{"id":"64583","key":"OPER-2348","self":"
https://jira.test/rest/api/latest/issue/64583"}
OPER-2348
Created issue OPER-2348



2016-05-30 8:46 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
This is possible if key 34 in Jira is not busy. For example if Jira project has the maximum issue key OPER-15. Then Lumper will create OPER-34. But if Jira project has 2 thousand issues then it is impossible to create issue with already occupied issue key.

**Comment by piskacek1** [comment]
It is possible to modify it?

2016-05-30 10:12 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
Modify Jira?

**Comment by piskacek1** [comment]
Hi,
my problem is issue id export and import issue key i need issue id = issue
key.

Because I have the tickets *issue id* 2001  in YT  and the next number is issue
id 3001. Jira automatically uses the number 2002 on import its bad for me :(



2016-05-30 10:31 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
Got it. I've added a new parameter to config file named `$maximumKeyGap`. Just set it to some appropriate value larger than your maximum gap between YT's issue keys (maybe 2000 will be enough).

**Comment by piskacek1** [comment]
you are master its OK !!!!! thanks

**Comment by piskacek1** [comment]
Hi Vitaly
I have one question ..link issue problem

   - Depends on
   - my mappink "Depend" => "Depend"  but not creating link :( in imports



2016-05-30 13:22 GMT+02:00 Vitaly Agapov <notifications@github.com>:

**Comment by agapoff** [comment]
Maybe your Jira does not have link type "Depend". By default it realy doesn't. You can try to map Depend to Blocks or Relates.

**Comment by patrikszo** [comment]
Hello. i am getting this issue:
./migrate.pl
Can't locate youtrack.pm in @INC (you may need to install the youtrack module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./migrate.pl line 3.

Does anyone know what could be wrong? Is the script usable in 2020? Thank you!

**Comment by agapoff** [comment]
@patrikszo I have pushed a small fix that would help you to use it in 2020. Enjoy :)

**Comment by patrikszo** [comment]
![image](https://user-images.githubusercontent.com/71184849/99790900-1588c000-2b25-11eb-87ec-211c61cdd5ed.png)

@agapoff  Thank you for the update. Could you please advise what is the youtrack.pm @INC module? I am still getting the same error.

**Comment by agapoff** [comment]
@patrikszo Are you sure that you have pulled the most recent change? Please run git log and check the latest commit.

**Comment by patrikszo** [comment]
![image](https://user-images.githubusercontent.com/71184849/99795062-71564780-2b2b-11eb-826c-f70dbfcd4775.png)
I am sorry, it was my mistake. thank you for pointing it out.
I have to find out now whats wrong, may be the Youtrack needs access token. The Lumper doesnt work with access token right?

**Comment by patrikszo** [comment]
I think the Youtrack does not supprt basic authentication with password and username. JIRA does. https://developer.atlassian.com/server/jira/platform/rest-apis/

**Comment by patrikszo** [comment]
if i follow exactly the instructions fot the login details in config.pl , it gives an error: 302 Moved Temporarily at youtrack.pm line 37.

**Comment by agapoff** [comment]
Most likely it redirects to https. Or just an API has changed in some way.

**Comment by patrikszo** [comment]
For me the way which worked is our $YTUrl='https://youtrack.company.eu';
For now, stucked again while login to JIRA. I will post an update if the script is working or not.
Thank you.

**Comment by patrikszo** [comment]
Unfortunately it returned 401 - Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html

**Comment by patrikszo** [comment]
Login has been solved, its ok to just use the API token instead of the password. 
But still its not working - looks REST API of YouTrack has changed and after successful login to JIRA and YouTrack it fails: syntax error at line 1, column 0, byte 0 at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/Parser.pm line 187.

https://www.jetbrains.com/help/youtrack/standalone/openapi-specification.html

**Comment by patrikszo** [comment]
Login has been solved, its ok to just use the API token instead of the password.
After successful login to JIRA and YouTrack it fails: syntax error at line 1, column 0, byte 0 at /usr/lib/x86_64-linux-gnu/perl5/5.30/XML/Parser.pm line 187.

I think there is syntax error at line 46 in file youtrack.pm :

my $response = $ua->get($self->{url}.'/rest/issue/'.$arg{IssueKey}.'/attachment', Cookie => $self->{cookie});

because REST API of YouTrack has changed and the queries need to be checked and fixed. (https://www.jetbrains.com/help/youtrack/standalone/openapi-specification.html).
